### ISSUE TITLE
error deploy in heroku

### ISSUE THREAD

**Issue by CARocha** [robotex82/simple_form-datetimepicker#19]
Hello i have rails 3.1.2 and rails 6.1.7, but when a try to deploy in heroku a see this error any idea? 

2022-11-04T21:40:15.608414+00:00 app[web.1]: => Booting Puma
2022-11-04T21:40:15.608458+00:00 app[web.1]: => Rails 6.1.7 application starting in production
2022-11-04T21:40:15.608458+00:00 app[web.1]: => Run `bin/rails server --help` for more startup options
2022-11-04T21:40:16.338713+00:00 app[web.1]: Exiting

2022-11-04T21:40:16.341100+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/simple_form-datetimepicker-0.0.3/app/inputs/date_picker_input.rb:1:in `<main>': uninitialized constant SimpleForm::Inputs (NameError)
2022-11-04T21:40:16.341101+00:00 app[web.1]: 
2022-11-04T21:40:16.341102+00:00 app[web.1]: class DatePickerInput < SimpleForm::Inputs::StringInput
2022-11-04T21:40:16.341106+00:00 app[web.1]: ^^^^^^^^

2022-11-04T21:40:16.341109+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'

**Comment by robotex82** [comment]
Do you mind posting you Gemfile?

**Comment by CARocha** [comment]
Hi, of course

https://pastebin.com/Ws5ZUmNW

Thanks

**Comment by robotex82** [comment]
Can you please try to add:

    gem 'simple_form'

before line 36 in your Gemfile or updating to the most recent current master? Version 0.0.3 is missing the require for simple_form.

**Comment by CARocha** [comment]
Ok thank, is solved! add simple_form in my Gemfile
